language: go
go:
 - 1.5.1
 - 1.6
 - tip

install:
- go get github.com/clevergo/cache
- go get github.com/julienschmidt/httprouter
- go get github.com/clevergo/ini
- go get github.com/clevergo/jwt
- go get github.com/clevergo/log
- go get github.com/hoisie/mustache
- go get github.com/clevergo/session

services:
  - redis-server

script:
 - go test -v ./...